### ISSUE TITLE
IronRouter using incorrect values

### ISSUE THREAD

**Issue by flanamacca** [jamesdwilson/meteor-jw-opinionated-skeleton#3]
Hey mate,

Noticed that your iron router config doesn't work when meter is updated.

Need to change:
Router.configure
  layout: 'layout'
  notFoundTemplate: 'notfound'
  loadingTemplate: 'loading'
  waitOn: Subscriptions
  renderTemplates:
    'nav':
      to: 'nav'

to 

Router.configure
  layoutTemplate: 'layout'
  notFoundTemplate: 'notfound'
  loadingTemplate: 'loading'
  waitOn: Subscriptions
  yieldTemplates:
    'nav':
      to: 'nav'

**Comment by jamesdwilson** [comment]
thanks! I don't have much time to work on it at the moment, would welcome a
pr!

James Wilson

**Comment by flanamacca** [comment]
Happily bud. Found your repo just looking for a few skeletons and wanting
to setup some defaults for my own apps

Will push through tonight - really like the foundations!  I've changed it
to support bootstrap3 as the only other basic change.

And its fun to get back into coffeescript haha

**Comment by jamesdwilson** [comment]
excellent! thank you much!

James Wilson

**Comment by jamesdwilson** [comment]
merged and added credit to you in the readme
thanks!

James Wilson

**Comment by flanamacca** [comment]
No worries mate - might want to also update the Meteor Version on the
readme :)

Yey for social coding haha

On Mon, Jan 6, 2014 at 5:36 PM, jamesdwilson notifications@github.comwrote:

> merged and added credit to you in the readme
> thanks!
> 
> James Wilson
> 
> On Sun, Jan 5, 2014 at 11:22 PM, Roland Flanagan
> notifications@github.comwrote:
> 
> > Happily bud. Found your repo just looking for a few skeletons and
> > wanting
> > to setup some defaults for my own apps
> > 
> > Will push through tonight - really like the foundations! I've changed it
> > to support bootstrap3 as the only other basic change.
> > 
> > And its fun to get back into coffeescript haha
> > On Jan 6, 2014 4:20 PM, "jamesdwilson" notifications@github.com
> > wrote:
> > 
> > > thanks! I don't have much time to work on it at the moment, would
> > > welcome
> > > a
> > > pr!
> > > 
> > > James Wilson
> > > 
> > > On Sun, Jan 5, 2014 at 8:41 PM, Roland Flanagan <
> > > notifications@github.com>wrote:
> > > 
> > > > Hey mate,
> > > > 
> > > > Noticed that your iron router config doesn't work when meter is
> > > > updated.
> > > > 
> > > > Need to change:
> > > > Router.configure
> > > > layout: 'layout'
> > > > notFoundTemplate: 'notfound'
> > > > loadingTemplate: 'loading'
> > > > waitOn: Subscriptions
> > > > renderTemplates:
> > > > 'nav':
> > > > to: 'nav'
> > > > 
> > > > to
> > > > 
> > > > Router.configure
> > > > layoutTemplate: 'layout'
> > > > notFoundTemplate: 'notfound'
> > > > loadingTemplate: 'loading'
> > > > waitOn: Subscriptions
> > > > yieldTemplates:
> > > > 'nav':
> > > > to: 'nav'
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3>
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31628165>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31628200>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31630168
> .

## 

Regards

Roland Flanagan

**Comment by jamesdwilson** [comment]
what version did you update it to?

James Wilson

**Comment by flanamacca** [comment]
0.7.0.1 -  latest :)

On Tue, Jan 7, 2014 at 10:23 AM, jamesdwilson notifications@github.comwrote:

> what version did you update it to?
> 
> James Wilson
> 
> On Mon, Jan 6, 2014 at 5:13 PM, Roland Flanagan notifications@github.comwrote:
> 
> > No worries mate - might want to also update the Meteor Version on the
> > readme :)
> > 
> > Yey for social coding haha
> > 
> > On Mon, Jan 6, 2014 at 5:36 PM, jamesdwilson notifications@github.comwrote:
> > 
> > > merged and added credit to you in the readme
> > > thanks!
> > > 
> > > James Wilson
> > > 
> > > On Sun, Jan 5, 2014 at 11:22 PM, Roland Flanagan
> > > notifications@github.comwrote:
> > > 
> > > > Happily bud. Found your repo just looking for a few skeletons and
> > > > wanting
> > > > to setup some defaults for my own apps
> > > > 
> > > > Will push through tonight - really like the foundations! I've
> > > > changed
> > > > it
> > > > to support bootstrap3 as the only other basic change.
> > > > 
> > > > And its fun to get back into coffeescript haha
> > > > On Jan 6, 2014 4:20 PM, "jamesdwilson" notifications@github.com
> > > > wrote:
> > > > 
> > > > > thanks! I don't have much time to work on it at the moment, would
> > > > > welcome
> > > > > a
> > > > > pr!
> > > > > 
> > > > > James Wilson
> > > > > 
> > > > > On Sun, Jan 5, 2014 at 8:41 PM, Roland Flanagan <
> > > > > notifications@github.com>wrote:
> > > > > 
> > > > > > Hey mate,
> > > > > > 
> > > > > > Noticed that your iron router config doesn't work when meter is
> > > > > > updated.
> > > > > > 
> > > > > > Need to change:
> > > > > > Router.configure
> > > > > > layout: 'layout'
> > > > > > notFoundTemplate: 'notfound'
> > > > > > loadingTemplate: 'loading'
> > > > > > waitOn: Subscriptions
> > > > > > renderTemplates:
> > > > > > 'nav':
> > > > > > to: 'nav'
> > > > > > 
> > > > > > to
> > > > > > 
> > > > > > Router.configure
> > > > > > layoutTemplate: 'layout'
> > > > > > notFoundTemplate: 'notfound'
> > > > > > loadingTemplate: 'loading'
> > > > > > waitOn: Subscriptions
> > > > > > yieldTemplates:
> > > > > > 'nav':
> > > > > > to: 'nav'
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3>
> > > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31628165>
> > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31628200>
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31630168>
> > 
> > > .
> > 
> > ## 
> > 
> > Regards
> > 
> > Roland Flanagan
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31697861>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jamesdwilson/meteor-jw-opinionated-skeleton/issues/3#issuecomment-31698589
> .

## 

Regards

Roland Flanagan

**Comment by jamesdwilson** [comment]
updated readme. thanks!

James Wilson
