### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by dandv** [jamesdwilson/meteor-jw-opinionated-skeleton#6]
There are [actively maintained Meteor boilerplates](https://github.com/themeteorchef/base/issues/1), maybe delete this one to help users find the right package?

**Comment by dandv** [comment]
Would be nice to [archive the repo](https://help.github.com/articles/archiving-a-github-repository/)

**Comment by jamesdwilson** [comment]
thanks, didn't know about this feature!
